### ISSUE TITLE
Not work on touchscreen

### ISSUE THREAD

**Issue by chenxiex** [christoph-heinrich/pointer_event#2]
My environment is ubuntu22.04.1 with gnome on wayland. The mouse click events work fine, but the touchscreen doesn't work properly. I use the example, but when I single tap the screen, it calls the uosc menu, and I can't close the menu by any gestures. What's worse, the dragging events don't work at all on touch screen.

**Comment by christoph-heinrich** [comment]
Works for me on my microsoft surface running kde plasma on wayland, but I have noticed that I have to move the mouse over the window after opening mpv for touch input to work properly. It doesn't matter if the mouse is on the window afterwards or not, but simply opening mpv with touch input and then trying to interact with touch without touching the mouse (touchpad) doesn't work as it should.

I haven't had time to investigate why that may be, but I have thought about how that behavior could come about and I have also noticed problems in another script under the same circumstances, so it might turn out that mpv doesn't send the events correctly until there was some actual mouse activity for some reason.

**Comment by chenxiex** [comment]
so it is a problem of gnome？ I haven't test on other de yet. And the solution I use now is set WAYLANＤ_DISPLAY to "". But in this case, vaapi doesn's work. I will leave the issue here and hope that someone can find a better solution.

**Comment by christoph-heinrich** [comment]
Might have something to do with https://github.com/mpv-player/mpv/issues/9771

**Comment by christoph-heinrich** [comment]
Has the commit that closed https://github.com/mpv-player/mpv/issues/9771 changed something for you?

**Comment by chenxiex** [comment]
Sorry for my late replay. I installed mpv 0.35.0 and it works! Awesome!

**Comment by chenxiex** [comment]
Sorry for my late reply. Building mpv-git on ubuntu is a little too difficult for me, since there are too many libs missing. I will wait for the next stable release.

**Comment by chenxiex** [comment]
I have switch to manjaro gnome wayland and build mpv from git. This is what happens:
If the window dragging is enabled and mpv in full screen, single click and drag will show the menu instead of play/pause.
If no-window-dragging is set, single click will perform play/pause, while dragging still doesn't work:  if I swipe on the screen for a short time, it performs play/pause; If I swipe for a long time, it shows the menu.

**Comment by christoph-heinrich** [comment]
I was about to ask you to give me a log with `--msg-level=pointer_event=trace`, but when i just tried it on my laptop, I managed to reproduce it _sometimes_, and when it happens it disappears as soon as I move the mouse. No idea how to trigger it reliably.
I've noticed that the events I get from mpv are different when it does work compared to when it doesn't work. Maybe I'll find some time this weekend to look into it some more.

**Comment by christoph-heinrich** [comment]
I still don't know which component of the stack is to blame for getting such inconsistent events, but the following patch works for me. Hopefully the same goes for you.

```diff
diff --git a/pointer-event.lua b/pointer-event.lua
index 01356c6..f6f0251 100644
--- a/pointer-event.lua
+++ b/pointer-event.lua
@@ -204,7 +204,7 @@ local function analyze_mouse(key)
 	end, {complex = true})
 	mp.observe_property('mouse-pos', 'native', function(name, mouse)
 		msg.trace(name, mouse.x, mouse.y, mouse.hover)
-		if mouse.hover and down_start then
+		if down_start then
 			if window_drag then btn_up()
 			else drag_to(mouse.x, mouse.y) end
 		end
```

**Comment by chenxiex** [comment]
> I still don't know which component of the stack is to blame for getting such inconsistent events, but the following patch works for me. Hopefully the same goes for you.
> 
> ```diff
> diff --git a/pointer-event.lua b/pointer-event.lua
> index 01356c6..f6f0251 100644
> --- a/pointer-event.lua
> +++ b/pointer-event.lua
> @@ -204,7 +204,7 @@ local function analyze_mouse(key)
>  	end, {complex = true})
>  	mp.observe_property('mouse-pos', 'native', function(name, mouse)
>  		msg.trace(name, mouse.x, mouse.y, mouse.hover)
> -		if mouse.hover and down_start then
> +		if down_start then
>  			if window_drag then btn_up()
>  			else drag_to(mouse.x, mouse.y) end
>  		end
> ```

This also works for me. Now the only problem is that the uosc menu cannot be touched (it seems to recognize touch event as mouse hover) , but I guess this has nothing to do with this repo. I will close the issue. But I suggest to mentioned this patch in README. Thanks for your help!

**Comment by christoph-heinrich** [comment]
> Now the only problem is that the uosc menu cannot be touched

I've tried to change that yesterday as well, but the problem is that touch events sometimes send the mouse position with `hover=false`, which generally means that the mouse left the window, resulting in that incorrect behavior. Ignoring `hover` makes it work (just like it did here), but without that it can't detect that the mouse left the window anymore.

Interestingly when I have the keyboard attached on my microsoft surface I usually (but not always) get touch events with `hover=true` (just like mouse input), but when I detach the keyboard before starting mpv the events get sent with `hover=false`. Detaching the keyboard after opening mpv does not result in this.

> But I suggest to mentioned this patch in README

I'll make a new release with that change.
